import '~/_styles/globals.css'
import type { Metadata } from 'next'
import ClientWrapper from '~/_providers/client-wrapper'
import { cn } from '~/_lib/utils'
import { ibmPlexSansThai, ibmPlexSansThaiLooped, poppins } from '~/_lib/fonts'

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        className={cn(
          poppins.variable,
          ibmPlexSansThai.variable,
          ibmPlexSansThaiLooped.variable,
          'flex justify-center bg-white'
        )}
      >
        {/* Recolor to white when finish dev*/}
        <div className='no-scrollbar flex h-screen w-[375px] items-start justify-start overflow-y-auto overflow-x-hidden bg-white px-6 pb-28 pt-[7.5rem]'>
          <ClientWrapper>{children}</ClientWrapper>
        </div>
      </body>
    </html>
  )
}
